# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data_sharing_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1esensor_data_sharing_grpc.proto\x12\x18sensor_data_sharing_grpc"(\n\x18SensorDataSharingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t")\n\x19SensorDataSharingResponse\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\x9a\x01\n\x15SensorDataSharingGrpc\x12\x80\x01\n\x13sensor_data_sharing\x12\x32.sensor_data_sharing_grpc.SensorDataSharingRequest\x1a\x33.sensor_data_sharing_grpc.SensorDataSharingResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "sensor_data_sharing_grpc_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SENSORDATASHARINGREQUEST._serialized_start = 60
    _SENSORDATASHARINGREQUEST._serialized_end = 100
    _SENSORDATASHARINGRESPONSE._serialized_start = 102
    _SENSORDATASHARINGRESPONSE._serialized_end = 143
    _SENSORDATASHARINGGRPC._serialized_start = 146
    _SENSORDATASHARINGGRPC._serialized_end = 300
# @@protoc_insertion_point(module_scope)
