# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import sensor_data_sharing_grpc_pb2 as sensor__data__sharing__grpc__pb2


class SensorDataSharingGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sensor_data_sharing = channel.unary_unary(
            "/sensor_data_sharing_grpc.SensorDataSharingGrpc/sensor_data_sharing",
            request_serializer=sensor__data__sharing__grpc__pb2.SensorDataSharingRequest.SerializeToString,
            response_deserializer=sensor__data__sharing__grpc__pb2.SensorDataSharingResponse.FromString,
        )


class SensorDataSharingGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sensor_data_sharing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SensorDataSharingGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "sensor_data_sharing": grpc.unary_unary_rpc_method_handler(
            servicer.sensor_data_sharing,
            request_deserializer=sensor__data__sharing__grpc__pb2.SensorDataSharingRequest.FromString,
            response_serializer=sensor__data__sharing__grpc__pb2.SensorDataSharingResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "sensor_data_sharing_grpc.SensorDataSharingGrpc", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SensorDataSharingGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sensor_data_sharing(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sensor_data_sharing_grpc.SensorDataSharingGrpc/sensor_data_sharing",
            sensor__data__sharing__grpc__pb2.SensorDataSharingRequest.SerializeToString,
            sensor__data__sharing__grpc__pb2.SensorDataSharingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
