# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
#   Copyright 99Cloud, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

"""Client and server classes corresponding to protobuf-defined services."""
import grpc # type: ignore

from . import (
    cooperative_lane_change_grpc_pb2 as cooperative__lane__change__grpc__pb2,
)  # noqa


class CooperativeLaneChangeGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel): # noqa
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cooperative_lane_change = channel.unary_unary(
            "/cooperative_lane_change_grpc.CooperativeLaneChangeGrpc/cooperative_lane_change",  # noqa
            request_serializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeRequest.SerializeToString,  # noqa
            response_deserializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeResponse.FromString,  # noqa
        )


class CooperativeLaneChangeGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cooperative_lane_change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CooperativeLaneChangeGrpcServicer_to_server(servicer, server): # noqa
    rpc_method_handlers = {
        "cooperative_lane_change": grpc.unary_unary_rpc_method_handler(
            servicer.cooperative_lane_change,
            request_deserializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeRequest.FromString,  # noqa
            response_serializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeResponse.SerializeToString,  # noqa
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cooperative_lane_change_grpc.CooperativeLaneChangeGrpc",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CooperativeLaneChangeGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cooperative_lane_change(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ): # noqa
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cooperative_lane_change_grpc.CooperativeLaneChangeGrpc/cooperative_lane_change",  # noqa
            cooperative__lane__change__grpc__pb2.CooperativeLaneChangeRequest.SerializeToString,  # noqa
            cooperative__lane__change__grpc__pb2.CooperativeLaneChangeResponse.FromString,  # noqa
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
