# -*- coding: utf-8 -*-
#   Copyright 99Cloud, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cooperative_lane_change_grpc.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf.internal import builder as _builder
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"cooperative_lane_change_grpc.proto\x12\x1c\x63ooperative_lane_change_grpc",\n\x1c\x43ooperativeLaneChangeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t"-\n\x1d\x43ooperativeLaneChangeResponse\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\xb2\x01\n\x19\x43ooperativeLaneChangeGrpc\x12\x94\x01\n\x17\x63ooperative_lane_change\x12:.cooperative_lane_change_grpc.CooperativeLaneChangeRequest\x1a;.cooperative_lane_change_grpc.CooperativeLaneChangeResponse"\x00\x62\x06proto3'  # noqa
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "cooperative_lane_change_grpc_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa
    DESCRIPTOR._options = None
    _COOPERATIVELANECHANGEREQUEST._serialized_start = 68  # noqa
    _COOPERATIVELANECHANGEREQUEST._serialized_end = 112  # noqa
    _COOPERATIVELANECHANGERESPONSE._serialized_start = 114  # noqa
    _COOPERATIVELANECHANGERESPONSE._serialized_end = 159  # noqa
    _COOPERATIVELANECHANGEGRPC._serialized_start = 162  # noqa
    _COOPERATIVELANECHANGEGRPC._serialized_end = 340  # noqa
# @@protoc_insertion_point(module_scope)
