# -*- coding: utf-8 -*-
"""
Created on Wed May 18 17:03:06 2022

@author: Polaris
"""


from pre_process_ai_algo.algo_lib.fusion import Fusion


def test_fusion():
    origin_radar_data = {
        "ab00000de": [
            {
                "guid": "ab00000de",
                "source": 3,
                "ptcId": 1,
                "width": 1.8,
                "length": 3.8,
                "secMark": 59060,
                "timeStamp": 59060,
                "ptcType": "motor",
                "x": 90.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "source": 3,
                "ptcId": 1,
                "secMark": 59110,
                "timeStamp": 59110,
                "ptcType": "motor",
                "x": 91,
                "y": 100,
                "width": 1.8,
                "length": 3.8,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "source": 3,
                "ptcId": 1,
                "secMark": 59160,
                "timeStamp": 59160,
                "ptcType": "motor",
                "width": 1.8,
                "length": 3.8,
                "x": 91.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "source": 3,
                "ptcId": 1,
                "secMark": 59210,
                "timeStamp": 59210,
                "ptcType": "motor",
                "width": 1.8,
                "length": 3.8,
                "x": 92,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "source": 3,
                "ptcId": 1,
                "secMark": 59260,
                "timeStamp": 59260,
                "width": 1.8,
                "length": 3.8,
                "ptcType": "motor",
                "x": 92.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59310,
                "timeStamp": 59310,
                "ptcType": "motor",
                "x": 93,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59360,
                "timeStamp": 59360,
                "ptcType": "motor",
                "x": 93.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59410,
                "timeStamp": 59410,
                "ptcType": "motor",
                "x": 94,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59460,
                "timeStamp": 59460,
                "ptcType": "motor",
                "x": 94.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59510,
                "timeStamp": 59510,
                "ptcType": "motor",
                "x": 95,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59560,
                "timeStamp": 59560,
                "ptcType": "motor",
                "x": 95.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59610,
                "timeStamp": 59610,
                "source": 3,
                "ptcId": 1,
                "ptcType": "motor",
                "x": 96,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59660,
                "timeStamp": 59660,
                "source": 3,
                "ptcId": 1,
                "ptcType": "motor",
                "x": 96.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59710,
                "timeStamp": 59710,
                "ptcType": "motor",
                "x": 97,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59760,
                "timeStamp": 59760,
                "source": 3,
                "ptcId": 1,
                "ptcType": "motor",
                "x": 97.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59810,
                "timeStamp": 59810,
                "ptcId": 1,
                "source": 3,
                "ptcType": "motor",
                "x": 98,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "source": 3,
                "ptcId": 1,
                "secMark": 59860,
                "timeStamp": 59860,
                "ptcType": "motor",
                "x": 98.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59910,
                "timeStamp": 59910,
                "ptcId": 1,
                "source": 3,
                "ptcType": "motor",
                "x": 99,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
            {
                "guid": "ab00000de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59960,
                "timeStamp": 59960,
                "ptcId": 1,
                "source": 3,
                "ptcType": "motor",
                "x": 99.5,
                "y": 100,
                "speed": 500,
                "heading": 7200,
            },
        ],
        "ab00001de": [
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59060,
                "timeStamp": 59060,
                "ptcId": 12,
                "source": 4,
                "ptcType": "motor",
                "x": 90,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59110,
                "timeStamp": 59110,
                "ptcId": 12,
                "source": 4,
                "ptcType": "motor",
                "x": 90.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59160,
                "timeStamp": 59160,
                "source": 4,
                "ptcId": 12,
                "ptcType": "motor",
                "x": 91,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59210,
                "timeStamp": 59210,
                "source": 4,
                "ptcType": "motor",
                "x": 91.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59260,
                "timeStamp": 59260,
                "ptcId": 12,
                "source": 4,
                "ptcType": "motor",
                "x": 92,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59310,
                "timeStamp": 59310,
                "ptcId": 12,
                "source": 4,
                "ptcType": "motor",
                "x": 92.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59360,
                "timeStamp": 59360,
                "source": 4,
                "ptcType": "motor",
                "x": 93,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59410,
                "timeStamp": 59410,
                "source": 4,
                "ptcType": "motor",
                "x": 93.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59460,
                "timeStamp": 59460,
                "source": 4,
                "ptcType": "motor",
                "x": 94,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59510,
                "timeStamp": 59510,
                "source": 4,
                "ptcType": "motor",
                "x": 94.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "ptcId": 12,
                "width": 1.8,
                "length": 3.8,
                "secMark": 59560,
                "timeStamp": 59560,
                "source": 4,
                "ptcType": "motor",
                "x": 95,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59610,
                "timeStamp": 59610,
                "source": 4,
                "ptcType": "motor",
                "x": 95.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59660,
                "timeStamp": 59660,
                "source": 4,
                "ptcType": "motor",
                "x": 96,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59710,
                "timeStamp": 59710,
                "source": 4,
                "ptcType": "motor",
                "x": 96.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59760,
                "timeStamp": 59760,
                "source": 4,
                "ptcType": "motor",
                "x": 97,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "ptcId": 12,
                "secMark": 59810,
                "timeStamp": 59810,
                "source": 4,
                "ptcType": "motor",
                "x": 97.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "source": 4,
                "ptcId": 12,
                "secMark": 59860,
                "timeStamp": 59860,
                "ptcType": "motor",
                "x": 98,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59910,
                "timeStamp": 59910,
                "ptcId": 12,
                "source": 4,
                "ptcType": "motor",
                "x": 98.5,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
            {
                "guid": "ab00001de",
                "width": 1.8,
                "length": 3.8,
                "secMark": 59960,
                "timeStamp": 59960,
                "ptcId": 12,
                "source": 4,
                "ptcType": "motor",
                "x": 99,
                "y": 100,
                "speed": 1000,
                "heading": 7200,
            },
        ],
    }
    lastest_frame_data = {
        "ab00000de": {
            "guid": "ab00000de",
            "width": 1.8,
            "length": 3.8,
            "ptcType": "motor",
            "ptcId": 1,
            "source": 3,
            "secMark": 10,
            "timeStamp": 60010,
            "x": 100,
            "y": 100,
            "speed": 500,
            "heading": 7200,
        },
        "ab00001de": {
            "guid": "ab00001de",
            "width": 1.8,
            "length": 3.8,
            "secMark": 10,
            "timeStamp": 60010,
            "ptcId": 12,
            "source": 4,
            "ptcType": "motor",
            "x": 99.5,
            "y": 100,
            "speed": 1000,
            "heading": 7200,
        },
    }

    matchPairs = {}  # 若没有前期历史数据就为空。

    historical_frames = origin_radar_data
    current_frame = lastest_frame_data
    last_timestamp = 59960
    DF = Fusion()
    rebuildData, last_timestamp, matchPairs = DF.run(
        historical_frames, current_frame, last_timestamp, matchPairs
    )

    assert matchPairs["ab00000de"] == ["ab00000de", "ab00001de"]
    assert rebuildData["ab00000de"]["x"] == 99.77843475341797
    assert rebuildData["ab00000de"]["y"] == 100.07427215576172
    assert rebuildData["ab00000de"]["source"] == 7
