# -*- coding: utf-8 -*-
#   Copyright 99Cloud, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data_sharing_grpc.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf.internal import builder as _builder
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1esensor_data_sharing_grpc.proto\x12\x18sensor_data_sharing_grpc"(\n\x18SensorDataSharingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t")\n\x19SensorDataSharingResponse\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\x9a\x01\n\x15SensorDataSharingGrpc\x12\x80\x01\n\x13sensor_data_sharing\x12\x32.sensor_data_sharing_grpc.SensorDataSharingRequest\x1a\x33.sensor_data_sharing_grpc.SensorDataSharingResponse"\x00\x62\x06proto3'  # noqa
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "sensor_data_sharing_grpc_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa
    DESCRIPTOR._options = None
    _SENSORDATASHARINGREQUEST._serialized_start = 60  # noqa
    _SENSORDATASHARINGREQUEST._serialized_end = 100  # noqa
    _SENSORDATASHARINGRESPONSE._serialized_start = 102  # noqa
    _SENSORDATASHARINGRESPONSE._serialized_end = 143  # noqa
    _SENSORDATASHARINGGRPC._serialized_start = 146  # noqa
    _SENSORDATASHARINGGRPC._serialized_end = 300  # noqa
# @@protoc_insertion_point(module_scope)
