# -*- coding: utf-8 -*-  # noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!  # noqa
# source: reverse_driving_grpc.proto  # noqa
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf.internal import builder as _builder
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1areverse_driving_grpc.proto\x12\x14reverse_driving_grpc"%\n\x15ReverseDrivingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t"&\n\x16ReverseDrivingResponse\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\x84\x01\n\x12ReverseDrivingGrpc\x12n\n\x0freverse_driving\x12+.reverse_driving_grpc.ReverseDrivingRequest\x1a,.reverse_driving_grpc.ReverseDrivingResponse"\x00\x62\x06proto3'  # noqa
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "reverse_driving_grpc_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa
    DESCRIPTOR._options = None
    _REVERSEDRIVINGREQUEST._serialized_start = 52  # noqa
    _REVERSEDRIVINGREQUEST._serialized_end = 89  # noqa
    _REVERSEDRIVINGRESPONSE._serialized_start = 91  # noqa
    _REVERSEDRIVINGRESPONSE._serialized_end = 129  # noqa
    _REVERSEDRIVINGGRPC._serialized_start = 132  # noqa
    _REVERSEDRIVINGGRPC._serialized_end = 264  # noqa
# @@protoc_insertion_point(module_scope)
