# -*- coding: utf-8 -*-
#   Copyright 99Cloud, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_not_pass_grpc.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf.internal import builder as _builder
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x64o_not_pass_grpc.proto\x12\x10\x64o_not_pass_grpc" \n\x10\x44oNotPassRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t"!\n\x11\x44oNotPassResponse\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2i\n\rDoNotPassGrpc\x12X\n\x0b\x64o_not_pass\x12".do_not_pass_grpc.DoNotPassRequest\x1a#.do_not_pass_grpc.DoNotPassResponse"\x00\x62\x06proto3'  # noqa
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "do_not_pass_grpc_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:  # noqa
    DESCRIPTOR._options = None
    _DONOTPASSREQUEST._serialized_start = 44  # noqa
    _DONOTPASSREQUEST._serialized_end = 76  # noqa
    _DONOTPASSRESPONSE._serialized_start = 78  # noqa
    _DONOTPASSRESPONSE._serialized_end = 111  # noqa
    _DONOTPASSGRPC._serialized_start = 113  # noqa
    _DONOTPASSGRPC._serialized_end = 218  # noqa
# @@protoc_insertion_point(module_scope)
