# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import (
    cooperative_lane_change_grpc_pb2 as cooperative__lane__change__grpc__pb2,
)


class CooperativeLaneChangeGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cooperative_lane_change = channel.unary_unary(
            "/cooperative_lane_change_grpc.CooperativeLaneChangeGrpc/cooperative_lane_change",
            request_serializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeRequest.SerializeToString,
            response_deserializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeResponse.FromString,
        )


class CooperativeLaneChangeGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cooperative_lane_change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CooperativeLaneChangeGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "cooperative_lane_change": grpc.unary_unary_rpc_method_handler(
            servicer.cooperative_lane_change,
            request_deserializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeRequest.FromString,
            response_serializer=cooperative__lane__change__grpc__pb2.CooperativeLaneChangeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cooperative_lane_change_grpc.CooperativeLaneChangeGrpc",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CooperativeLaneChangeGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cooperative_lane_change(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cooperative_lane_change_grpc.CooperativeLaneChangeGrpc/cooperative_lane_change",
            cooperative__lane__change__grpc__pb2.CooperativeLaneChangeRequest.SerializeToString,
            cooperative__lane__change__grpc__pb2.CooperativeLaneChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
