# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import collision_grpc_pb2 as collision__grpc__pb2


class CollisionGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.collision = channel.unary_unary(
            "/collision_grpc.CollisionGrpc/collision",
            request_serializer=collision__grpc__pb2.CollisionRequest.SerializeToString,
            response_deserializer=collision__grpc__pb2.CollisionResponse.FromString,
        )


class CollisionGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def collision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CollisionGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "collision": grpc.unary_unary_rpc_method_handler(
            servicer.collision,
            request_deserializer=collision__grpc__pb2.CollisionRequest.FromString,
            response_serializer=collision__grpc__pb2.CollisionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "collision_grpc.CollisionGrpc", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CollisionGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def collision(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/collision_grpc.CollisionGrpc/collision",
            collision__grpc__pb2.CollisionRequest.SerializeToString,
            collision__grpc__pb2.CollisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
