name: ci-base

on:
  push:
    branches:
      - columbia

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-cerebrum-base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: openv2x/cerebrum-base:columbia
          build-args: |
            GIT_BRANCH=${{ github.ref_name }}
            REPO_URL=https://github.com/open-v2x/cerebrum
            GIT_COMMIT=${{ github.sha }}

  acr:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: sync image to ACR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FQ_HOST }}
          username: ${{ secrets.FQ_USERNAME }}
          key: ${{ secrets.FQ_KEY }}
          port: ${{ secrets.FQ_PORT }}
          script: |
            set -e

            (docker images | grep none | awk '{print $3}' | xargs -I{} docker rmi -f {}) || true
            docker pull openv2x/cerebrum-base:columbia
            docker tag openv2x/cerebrum-base:columbia registry.cn-shanghai.aliyuncs.com/openv2x/cerebrum-base:columbia
            docker push registry.cn-shanghai.aliyuncs.com/openv2x/cerebrum-base:columbia
