name: test

on:
  pull_request:
    branches:
      - 'master'
env:
  OPENV2X_EXTERNAL_IP: 127.0.0.1
  OPENV2X_CENTER_IP: 127.0.0.1
  OPENV2X_IS_CENTER: true
  OPENV2X_REDIS_ROOT: password
  OPENV2X_MARIADB_ROOT: password
  OPENV2X_MARIADB_DANDELION: password
  OPENV2X_EMQX_ROOT: password
  redis_host: '127.0.0.1'
  mqtt_host: '127.0.0.1'
  mysql_host: '127.0.0.1'
  cloud_url: 'http://127.0.0.1:28300/api/v1'
  mysql_user: 'root'
  mysql_password: password
  emqx_password: password
  redis_password: password

jobs:

  function_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: install pre
        run: sudo unalias cp 2>/dev/null || true
      - name: install pre
        run: sudo rm -rf openv2x-aio-master.tar.gz && wget https://openv2x.oss-ap-southeast-1.aliyuncs.com/deploy/master/openv2x-aio-master.tar.gz
      - name: install pre
        run: sudo rm -rf src && tar zxvf openv2x-aio-master.tar.gz
      - name: install pre
        run: sudo sed -i "s/8084/8085/" src/deploy/docker-compose-pre.yaml && sudo sed -i "s/8084/8085/" src/deploy/docker-compose-service.yaml
      - name: install openv2x
        run: cd src && chmod +x ./install.sh && sudo -E bash ./install.sh
      - name: stop cerebrum
        run: sudo docker stop cerebrum

      - name: pip install virtualenv
        run: pip install virtualenv
      - name: create virtual environment
        run: python -m virtualenv .venv
      - name: into virtual environment
        run: . .venv/bin/activate
      - name: install requirements
        run: pip install  -r requirements/algo.txt -r requirements.txt -r test-requirements.txt

      - name: run cerebrum service
        run: python main.py &
      
      - name: make pytest-cov invalid in tox.ini
        run: sed -i "s/^  --cov=pre_process_ai_algo/#&/" tox.ini

      - name: pip install test-function-requirements
        run: pip install -r test-function-requirements.txt
      - name: run test cases
        env:
          ip: 127.0.0.1
          emqx_root: password
        run: sh ./function_test/function_test.sh